const pages = [
  { id:'index.html', title:'메인 페이지', fields:[
    ['heroIntro','메인 소개','.hero-placeholder span','textarea'],['hotelHeading','호텔 영문 제목','.intro-copy h2','textarea'],['hotelIntro','호텔 소개','.intro-copy .content-placeholder span','textarea'],['worldCard','호텔과 신오 카드','.room-card .card-title','textarea'],['characterCard','투숙객 안내 카드','.salon-card .card-title','textarea'],['quote','중앙 강조 문구','.quote-placeholder span','textarea'],['notice1','공지 1 제목','.journal-list a:nth-child(1) p','text'],['notice2','공지 2 제목','.journal-list a:nth-child(2) p','text'],['notice3','공지 3 제목','.journal-list a:nth-child(3) p','text'],['applyInfo','하단 신청 안내','.visit-placeholder span','textarea'] ]},
  { id:'world.html', title:'세계관', fields:[['intro','상단 소개','.sub-hero > p:last-child','textarea'],['title1','세계관 제목','.chapter:nth-of-type(1) h2','text'],['body1','세계관 내용','.chapter:nth-of-type(1) .content-placeholder span','textarea'],['title2','호텔 연혁 제목','.chapter:nth-of-type(2) h2','text'],['body2','호텔 연혁 내용','.chapter:nth-of-type(2) .content-placeholder span','textarea'],['title3','비밀 설정 제목','.chapter:nth-of-type(3) h2','text'],['body3','비밀 설정 내용','.chapter:nth-of-type(3) .content-placeholder span','textarea'],['extra','추가 안내','.rules-panel .content-placeholder span','textarea']]},
  { id:'character-guide.html', title:'캐릭터 가이드', fields:[['intro','상단 소개','.sub-hero > p:last-child','textarea'],['basic','기본 설정 안내','.guide-grid article:nth-child(1) .content-placeholder span','textarea'],['reason','입장 계기 안내','.guide-grid article:nth-child(2) .content-placeholder span','textarea'],['rules','작성 유의사항','.guide-grid article:nth-child(3) .content-placeholder span','textarea'],['sheet','신청서 링크','.quick-links a:nth-child(1)','url','href'],['form','신청 폼 링크','.quick-links a:nth-child(2)','url','href']]},
  { id:'system.html', title:'공용 시스템', fields:[['progress','진행 시스템','.system-grid article:nth-child(1) .content-placeholder span','textarea'],['event','이벤트','.system-grid article:nth-child(2) .content-placeholder span','textarea'],['schedule','일정표','.system-grid article:nth-child(3) .content-placeholder span','textarea'],['additional','기타 안내','.system-grid article:nth-child(4) .content-placeholder span','textarea']]},
  { id:'notice.html', title:'공지사항', fields:[['title1','공지 1 제목','.notice-list article:nth-child(1) h2','text'],['body1','공지 1 내용','.notice-list article:nth-child(1) .content-placeholder span','textarea'],['date1','공지 1 날짜','.notice-list article:nth-child(1) > b','text'],['title2','공지 2 제목','.notice-list article:nth-child(2) h2','text'],['body2','공지 2 내용','.notice-list article:nth-child(2) .content-placeholder span','textarea'],['date2','공지 2 날짜','.notice-list article:nth-child(2) > b','text'],['title3','공지 3 제목','.notice-list article:nth-child(3) h2','text'],['body3','공지 3 내용','.notice-list article:nth-child(3) .content-placeholder span','textarea'],['date3','공지 3 날짜','.notice-list article:nth-child(3) > b','text'],['contact','문의 안내','.contact-panel .content-placeholder span','textarea']]},
  { id:'guests.html', title:'직원 명부', fields:[...Array.from({length:4},(_,i)=>{const n=i+1;return [[`guest${n}Room`,`직원 ${n} 부서`,`.directory-grid > a:nth-child(${n}) > span`,'text'],[`guest${n}Name`,`직원 ${n} 이름`,`.directory-grid > a:nth-child(${n}) h2`,'text'],[`guest${n}Intro`,`직원 ${n} 소개`,`.directory-grid > a:nth-child(${n}) > p`,'text']]}).flat()]}
];

let activePage = pages[0];
let directoryHandle = null;
const data = structuredClone(window.THEOBROMA_CONTENT || {});
const pageNav = document.querySelector('#page-nav');
const form = document.querySelector('#content-form');

function renderNav(){pageNav.innerHTML='';pages.forEach(page=>{const button=document.createElement('button');button.type='button';button.textContent=page.title;button.classList.toggle('active',page.id===activePage.id);button.onclick=()=>{activePage=page;renderNav();renderForm()};pageNav.append(button)})}
function renderForm(){document.querySelector('#page-kicker').textContent=activePage.id;document.querySelector('#page-title').textContent=activePage.title;form.innerHTML='';activePage.fields.forEach(([key,label,selector,type,property])=>{const row=document.createElement('div');row.className='field-group';const labelEl=document.createElement('label');labelEl.htmlFor=key;labelEl.innerHTML=`${label}<span>${property==='href'?'연결 주소':'표시 문구'}</span>`;const input=document.createElement(type==='textarea'?'textarea':'input');input.id=key;input.name=key;if(type!=='textarea')input.type=type;input.value=data[activePage.id]?.[selector]?.[property||'text']||'';input.dataset.selector=selector;input.dataset.property=property||'text';row.append(labelEl,input);form.append(row)})}
function collect(){data[activePage.id] ||= {};form.querySelectorAll('input,textarea').forEach(input=>{data[activePage.id][input.dataset.selector] ||= {};data[activePage.id][input.dataset.selector][input.dataset.property]=input.value})}
function showMessage(text){const el=document.querySelector('#save-message');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2400)}
async function save(){if(!directoryHandle){showMessage('먼저 프로젝트 폴더를 선택해 주세요.');return}collect();const file=await directoryHandle.getFileHandle('site-content.js',{create:true});const writable=await file.createWritable();await writable.write(`window.THEOBROMA_CONTENT = ${JSON.stringify(data,null,2)};\n`);await writable.close();showMessage('저장했습니다. 사이트를 새로고침해 확인하세요.')}
document.querySelector('#choose-folder').onclick=async()=>{try{directoryHandle=await window.showDirectoryPicker({mode:'readwrite'});document.querySelector('#folder-status').textContent=`선택된 폴더: ${directoryHandle.name}`;showMessage('프로젝트 폴더가 연결되었습니다.')}catch(error){if(error.name!=='AbortError')showMessage('폴더를 열 수 없습니다.')}};
document.querySelector('#save').onclick=save;
renderNav();renderForm();
